server:
  port: 9092

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:dbChangeLog/master.xml

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

staticImageDirectory: "/src/main/resources/static/images/"
